shiritori/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stapp.urls')),
    path('accounts/', include('allauth.urls')),
]

stapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views




app_name = 'stapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('game/goal/', views.GoalView.as_view(), name='goal'),
    path('game/new/', views.new_game, name='new_game'),
    path('game/choice/', views.new_choice, name='new_choice'),
]

stapp/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

# Create your models here.

#都道府県テーブルはこれで確定。
#テーブル名MstPrefecture,属性はcdとnameで作り直すのもあり
#pkを自動生成されるidにしたくないければ明示が必要！
class Prefecture(models.Model):
    prf_no = models.IntegerField(default=0, unique=True, primary_key=True)
    prf_name = models.CharField(max_length=10)

    def __str__(self):
        return self.prf_name

#テスト用なのでガンガンいじっていこう
class MstTestStation(models.Model):
    no = models.IntegerField()
    name_kanji = models.CharField(max_length=100)
    name_hira = models.CharField(max_length=100)
    name_kata = models.CharField(max_length=100)
    first_letter = models.CharField(max_length=1)
    last_letter = models.CharField(max_length=1)
    is_ends_n = models.BooleanField()
    #ForeignKeyのon_deleteについて https://qiita.com/AJIKING/items/7448a6ad3cc2347ae4d5
    #都道府県テーブルを参照する駅名がある場合に、都道府県を削除できないようにする
    prf_no = models.ForeignKey(Prefecture, to_field='prf_no', on_delete=models.PROTECT)
    city_name = models.CharField(max_length=100)
    jr_co_name = models.CharField(max_length=100)
    rail_name = models.CharField(max_length=200)

    def __str__(self):
        return self.name_kanji + '（' + self.name_hira + '）'

class TestGame(models.Model):
    player = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    start_station = models.ForeignKey(MstTestStation, on_delete=models.PROTECT, related_name='start_staion')
    start_letter = models.CharField(max_length=1)
    goal_station = models.ForeignKey(MstTestStation, on_delete=models.PROTECT, related_name='goal_staion')
    goal_letter = models.CharField(max_length=1)
    start_date = models.DateTimeField(default=timezone.now)
    is_finished = models.BooleanField(default=False)

    def __str__(self):
        return 'from ' + self.start_station.name_kata + ' to ' + self.goal_station.name_kata

class TestChoice(models.Model):
    game = models.ForeignKey(TestGame, on_delete=models.CASCADE)
    station = models.ForeignKey(MstTestStation, on_delete=models.CASCADE)

    def __str__(self):
        return self.station.name_kata

stapp/forms.py
from django import forms

from .models import Prefecture, MstTestStation, TestGame, TestChoice

# createviewの機能でまかなうことにしたので、下記フォームはいったんコメントアウト
# 21/8/30 県名（親カテゴリ）で動的に絞り込むため復活
class TestGameForm(forms.ModelForm):
    
    start_prf = forms.ModelChoiceField(
        label = 'スタート都道府県',
        queryset = Prefecture.objects,
        required = False
    )

    goal_prf = forms.ModelChoiceField(
        label = 'ゴール都道府県',
        queryset = Prefecture.objects,
        required = False
    )


    class Meta:
        model = TestGame
        fields = ('start_prf','start_station','goal_prf', 'goal_station',)
        
        # widgetの種類　https://docs.djangoproject.com/en/3.2/ref/forms/widgets/#django.forms.SelectDateWidget
        '''widgets = {
            'start_station': forms.RadioSelect, 
            'goal_station': forms.RadioSelect,
        }'''



class TestChoiceForm(forms.ModelForm):

    class Meta:
        model = TestChoice
        fields = ('game','station')
        widgets = {
            'game': forms.HiddenInput,
        }

    # formが画面に表示される前に何をするかを定める
    def __init__(self, *args, **kwargs):
        # https://hideharaaws.hatenablog.com/entry/2017/02/05/021111
        self.start_letter = kwargs.pop('start_letter')
        self.game  = kwargs.pop('game')
        
        # https://sleepless-se.net/2018/07/10/django%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0%E5%86%85%E3%81%AE%E9%96%A2%E9%80%A3%E3%83%86%E3%83%BC%E3%83%96%E3%81%AB%E3%83%95%E3%82%A3%E3%83%AB%E3%82%BF%E3%83%BC%E3%82%92%E3%81%8B%E3%81%91%E3%82%8B/
        # ModelForm（親クラス）のinitメソッドを丸っと継承する（意味不明だがないと動かない）
        super().__init__(*args, **kwargs)
        
        # start_letter = kwargs.get("instance").start_letter
        # start_letter = kwargs.pop('start_letter')
        
        self.fields['game'].initial = self.game

        # https://codor.co.jp/django/about-filter
        self.fields['station'].queryset = MstTestStation.objects.filter(first_letter=self.start_letter)

        # super().__init__(*args, **kwargs)

    

stapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from urllib.parse import urlencode
from django.views import generic
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from .models import Prefecture, MstTestStation, TestGame, TestChoice
from .forms import TestChoiceForm, TestGameForm
from django.views.generic import CreateView, TemplateView


# Create your views here.

class IndexView(TemplateView):
    template_name = "index.html"

@method_decorator(login_required, name='dispatch')
class GoalView(TemplateView):
    template_name = "goal.html"



# new_gameもFormViewで書き換えられると思う　→ 8/29 書き換えた
# render(url)での変数受け渡しを脱する必要がある

'''関数ベースver
def new_game(request):

    if request.method == "POST":
        form = TestGameForm(request.POST) 
        
        # 入力内容のチェック
        if form.is_valid():
            game = form.save(commit=False) # 仮登録
            game.player = request.user

            # スタート地点の尻文字を、1選択目に渡したい
            game.start_letter = game.start_station.last_letter

            # ゴール地点の頭文字をゲームIDに登録しておく（ゴール判定に使いたいな）
            game.goal_letter = game.goal_station.first_letter

            # start_dateは登録日時が自動入力

            # DBに保存
            game.save()

            # 最初の駅選択に必要な情報を変数（dictionary型）にまとめ、url連結用に変換
            params = urlencode({
                'game': game.pk,
                'start_letter': game.start_letter,
                'goal_letter': game.goal_letter,
            })

            # 選択画面(urlのname='new_choice')のパスを取得
            redirect_url = reverse('stapp:new_choice')

            #ゲームIDを渡して選択画面へ移動＝'views.new_choice'を呼び出す
            url = f'{redirect_url}?{params}' # 'f'について　https://note.nkmk.me/python-f-strings/
            return redirect(url)
    else: # ← methodが'POST'ではない = 最初のページ表示時の処理
        form = TestGameForm()
    return render(request, 'new_game.html', {'form': form})
'''


# クラスベースビューに書き換え
# デコレータについて　https://programming.sincoston.com/django-classbaseview-decorator/
@method_decorator(login_required, name='dispatch')
class NewGame(CreateView):
    # model = TestGame
    # fields = ['start_station', 'goal_station']
    
    form_class = TestGameForm
    template_name = 'new_game.html'
    

    # templateに都道府県リストを渡す
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['parentcategory_list'] = Prefecture.objects.all()
        # context['station_list'] = MstTestStation.objects.filter(is_ends_n=False)
        return context


    # formに抜け漏れがなければ行う
    def form_valid(self, form):
        form.instance.player = self.request.user

        # スタート地点の尻文字を、1選択目に渡す
        # 'instance'がないとダメらしい
        form.instance.start_letter = form.instance.start_station.last_letter

        # ゴール地点の頭文字をゲームIDに登録しておく（ゴール判定に使う）
        form.instance.goal_letter = form.instance.goal_station.first_letter

        return super().form_valid(form)


    def get_success_url(self):
        # 最初の駅選択に必要な情報を変数（dictionary型）にまとめ、url連結用に変換
        params = urlencode({
            'game': self.object.pk,
            'start_letter': self.object.start_letter,
            'goal_letter': self.object.goal_letter,
        })

        # 選択画面(urlのname='new_choice')のパスを取得
        redirect_url = reverse('stapp:new_choice')

        #ゲームIDを渡して選択画面へ移動＝'views.new_choice'を呼び出す
        url = f'{redirect_url}?{params}' # 'f'について　https://note.nkmk.me/python-f-strings/
        
        return url

# as_view()はViewに付属の関数。
# クロージャであるview(request, *args, **kwargs)関数を返す
new_game = NewGame.as_view()


'''
memo: FormViewの処理の流れ（CreateViewもほぼ同じ）

    流れ（HTTP GET）
        as_view()で呼ばれて、HTTP methodがGETの場合、ProcessFormViewのdef getが呼ばれる
        FormMixin中のget_context_data()が呼ばれ、インスタンス変数のform_classがkwargs['form']に格納される
        今までと同様、templateをreturnする
    流れ（HTTP POST）
        as_view()で呼ばれて、HTTP methodがPOSTの場合、ProcessFormViewのdef postが呼ばれる
        FormMixinのget_form()が呼ばれ、値の挿入されたformを入手
        form.is_valid()でform classで定義されたvalidationの判定
        validであればFormMixinのform_valid(form)が呼ばれ, インスタンス変数のsuccess_urlにリダイレクトされる
        invlidであればエラーと一緒にGETにリダイレクトされる

'''


# レコードの新規作成は、文字通りCreateViewを使おう
# 21/8/28 createviewにしたことで、保存はできた→変数の受け取りなどどうするか
# 21/8/29 form使用を復活してフィルターと保存,変数を渡すのに成功！！！！！
@method_decorator(login_required, name='dispatch')
class NewChoice(CreateView):

    form_class = TestChoiceForm    # forms.pyの呼び出したいformを指定
    template_name = 'new_choice.html'  # 表示するtemplate



    # 1.new_gameもしくは前のchoiceから変数('game','start_letter')を受け取る
    # 2.受け取った変数を反映させたformを表示する
    # form に kwargs を渡す関数
    def get_form_kwargs(self):
        kwargs = super(NewChoice, self).get_form_kwargs() # 継承。ようわからん
        
        # 独自で変数を追加する
        kwargs['game'] = self.request.GET.get('game')
        kwargs['start_letter'] = self.request.GET.get('start_letter')

        return kwargs



    # 選択後に飛ぶurlを作る関数
    def get_success_url(self):
        
        # 選択を変数に格納
        chosen_station = self.object.station
        game = self.object.game

        # 選択駅がゴール駅だったらゴールのページに飛ぶ
        # ゴール判定は https://qiita.com/maisuto/items/33dfeb58f5953d1c5fdf の
        # 「投票処理」を参考にして実装
        if chosen_station == game.goal_station:
            url = reverse('stapp:goal')
            # return resolve_url('polls:results', self.kwargs['pk'])
            # しりとりの軌跡を表示したい

            # is_finishedをtrueに書き換える
            game_finished = get_object_or_404(TestGame, pk=game.pk)
            game_finished.is_finished = True
            game_finished.save()
        else:
            params = urlencode({
                'game': game.pk,
                'start_letter': chosen_station.last_letter,
            })

            # 選択画面(urlのname='new_choice')のパスを取得
            redirect_url = reverse('stapp:new_choice')

            #ゲームIDを渡して選択画面へ移動＝'views.new_choice'を呼び出す
            url = f'{redirect_url}?{params}' # 'f'について　https://note.nkmk.me/python-f-strings/
            
        return url


    '''def goal(pk):
        game = get_object_or_404(TestGame, pk=pk)
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "You didn't select a choice.",
            })
        else:
        game.is_finished = True
        game.save()
        #return reverse('stapp:goal')'''

new_choice = NewChoice.as_view()

stapp/templates/base.html
{% load static%}

<html lang="ja">

    <head>

        <meta charset="utf-8" />

        <title>{% block title %}{% endblock %}</title>

        <!-- Core theme CSS (includes Bootstrap)
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        -->

        <!---My style-->
        <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
        
        {% block head %}{% endblock %}

    </head>

    <body id="page-top">

        <!-- Navigation-->
        <nav>

            <a href="{% url 'stapp:index' %}">JR駅名しりとりの旅ゲーム</a>

            {% if user.is_authenticated %}
                <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'account_logout' %}">Log Out</a>)</small></p>
            {% else %}
                <p>
                    <a href="{% url 'account_signup' %}" class="top-menu">Sign Up</span></a>
                    <a href="{% url 'account_login' %}" class="top-menu">Log In</span></a>
                </p>
            {% endif %}

        </nav>
        
        {% block header %}{% endblock %}

        {% block contents %}{% endblock %}

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        {% block extrajs %}{% endblock %}

    </body>
        

</html>

stapp/templates/goal.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Goal｜JR駅名しりとりの旅ゲーム{% endblock %}

{% block header %}



{% endblock %}

{% block contents %}

<h2>Goal! Congratulations!!!</h2>

    <button onclick="location.href='{% url 'stapp:index' %}'" class="btn btn-primary btn-xl rounded-pill mt-5">Back</button>


{% endblock %}

stapp/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Top Page｜JR駅名しりとりの旅ゲーム{% endblock %}

{% block header %}

<header>
    <h1 class="masthead-heading mb-0">JR駅名しりとりの旅ゲーム</h1>
</header>

{% endblock %}

{% block contents %}

<section>

    <!---
    <div>
        <img class="icon" src="{% static 'assets/img/dg.jpg' %}" alt="">
    </div>
    -->

    <h2>
        <!---'stapp:'がないとurlを逆引きできなかった-->
        <a href="{% url 'stapp:new_game' %}">しりとりの旅を<br>始める</a>
    </h2>

</section>

{% endblock %}

stapp/templates/new_choice.html
{% extends 'base.html' %}

{% load static %}

{% block title %}New Choice｜JR駅名しりとりの旅ゲーム{% endblock %}

{% block header %}


{% endblock %}

{% block contents %}

<h2>New Choice</h2>
<form method="POST" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary btn-xl rounded-pill mt-5">Save</button>
</form>


{% endblock %}

stapp/templates/new_game.html
{% extends 'base.html' %}

{% load static %}

{% block title %}New Game｜JR駅名しりとりの旅ゲーム{% endblock %}

{% block header %}


{% endblock %}

{% block contents %}

    <h2>New Game</h2>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-xl rounded-pill mt-5">Save</button>
    </form>

{% endblock %}

{% block extrajs %}

    <script>

        // 選択した都道府県に合わせて駅名を表示

        
        // この'#id'はformのfield名と一致させる
        const parentCategoryElement = $('#id_start_prf');
        const categoryElement = $('#id_start_station');
        
        const goalPrfElement = $('#id_goal_prf');
        const goalStationElemnt = $('#id_goal_station');


        //categoriesはstartとgoalで共通部品
        const categories = {

            {% for prf in parentcategory_list %}
                '{{ prf.prf_no }}': [
                    {% for station in prf.mstteststation_set.all %}
                        {
                            'pk': '{{ station.pk }}',
                            'name': '{{ station }}'
                        },
                    {% endfor %}
                ],
            {% endfor %}

        };


        // for start_station
        const changeCategory = (select) => {
            // 子カテゴリの選択欄を空にする。
            categoryElement.children().remove();

            // 選択した親カテゴリに紐づく子カテゴリの一覧を取得する。
            const parentId = parentCategoryElement.val();
            const categoryList = categories[parentId];

            // 子カテゴリの選択肢を作成・追加。
            for (const category of categoryList) {
                const option = $('<option>');
                option.val(category['pk']);
                option.text(category['name']);
                categoryElement.append(option);
            }

            // 指定があれば、そのカテゴリを選択する
            if (select !== undefined) {
                categoryElement.val(select);
            }
        };


        $('#id_start_prf').on('change', () => {
            changeCategory();
        });


        // 入力値に問題があって再表示された場合、ページ表示時点で小カテゴリが絞り込まれるようにする
        if (parentCategoryElement.val()) {
            const selectedCategory = categoryElement.val();
            changeCategory(selectedCategory);
        }


        // for goal_station
        const changePrf = (select) => {
            // 子カテゴリの選択欄を空にする。
            goalStationElemnt.children().remove();

            // 選択した親カテゴリに紐づく子カテゴリの一覧を取得する。
            const prfId = goalPrfElement.val();
            const stationList = categories[prfId];

            // 子カテゴリの選択肢を作成・追加。
            for (const station of stationList) {
                const goalOption = $('<option>');
                goalOption.val(station['pk']);
                goalOption.text(station['name']);
                goalStationElemnt.append(goalOption);
            }

            // 指定があれば、そのカテゴリを選択する
            if (select !== undefined) {
                goalStationElemnt.val(select);
            }
        };


        $('#id_goal_prf').on('change', () => {
            changePrf();
        });


        // 入力値に問題があって再表示された場合、ページ表示時点で小カテゴリが絞り込まれるようにする
        if (goalPrfElement.val()) {
            const selectedStation = goalStationElemnt.val();
            changePrf(selectedStation);
        }

    </script>

{% endblock %}